version: '3.4'
services:
  api:
    build:
      context: .
      target: api
    ports:
      - "80:80"
    volumes:
      - logs:/var/log
    links:
      - database
    environment:
      APP_ENV: prod
      APP_SECRET: 3f2a40e36bfe197ba15f3743e778b0cb
      WAIT_HOSTS: database:5432
  database:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chez_nestor
      POSTGRES_USER: chez_nestor
      POSTGRES_PASSWORD: grez6gezHEZF54hz4rt6hrFEGEgdfs

volumes:
  logs: {}
  postgres: {}